
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140703 (SVN rev 36)
// Sat Apr 15 12:28:23 PDT 2017
//----------------------------------------------------

package com.cali;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DI = 50;
  public static final int GTEQ = 58;
  public static final int LBRACKET = 30;
  public static final int PL = 47;
  public static final int DIEQ = 43;
  public static final int LTEQ = 57;
  public static final int MI = 48;
  public static final int UMINUS = 52;
  public static final int PLPL = 45;
  public static final int MODULUSEQ = 44;
  public static final int CASE = 19;
  public static final int DOUBLE = 36;
  public static final int LPAREN = 28;
  public static final int PRIVATE = 7;
  public static final int SEMI = 25;
  public static final int CLASSDEF = 2;
  public static final int INT = 35;
  public static final int FOR = 23;
  public static final int MIMI = 46;
  public static final int INSTANCEOF = 24;
  public static final int STATIC = 8;
  public static final int RPAREN = 29;
  public static final int AND = 60;
  public static final int NOT = 59;
  public static final int LT = 55;
  public static final int ETCETERA = 63;
  public static final int OR = 61;
  public static final int BOOL = 34;
  public static final int COMMA = 27;
  public static final int THROW = 13;
  public static final int MUEQ = 42;
  public static final int EXTERN = 9;
  public static final int IF = 16;
  public static final int DOT = 66;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 31;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int INCLUDE = 4;
  public static final int EQEQ = 53;
  public static final int NULL = 15;
  public static final int TRY = 11;
  public static final int IDENT = 38;
  public static final int BREAK = 22;
  public static final int EQ = 39;
  public static final int SWITCH = 18;
  public static final int PLEQ = 40;
  public static final int COLON = 26;
  public static final int LBRACE = 32;
  public static final int ELSE = 17;
  public static final int PROTECTED = 6;
  public static final int CALLBACK = 64;
  public static final int ENUM = 3;
  public static final int WHILE = 21;
  public static final int INSERT = 65;
  public static final int MIEQ = 41;
  public static final int DEFAULT = 20;
  public static final int PUBLIC = 5;
  public static final int RBRACE = 33;
  public static final int MODULUS = 51;
  public static final int STRING = 37;
  public static final int COUNT = 62;
  public static final int GT = 56;
  public static final int MU = 49;
  public static final int NOTEQ = 54;
  public static final int CATCH = 12;
}

